# Docker compose v2 definition
# Run using docker compose up

services:
  web:
    build: ./docker/web
    ports:
      - 80:80
      - 443:443
    environment:
      - DB_HOST=mysql-db
      - PGSQL_HOST=postgresql-db
      - APPLICATION_ENV=development
    volumes:
      - .:/srv/osmhu-website
      - ./development/apache2/osmhu-http.conf:/etc/apache2/sites-enabled/osmhu-http.conf
      - ./development/apache2/osmhu-ssl.conf:/etc/apache2/sites-enabled/osmhu-ssl.conf
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=osmhu
      - MYSQL_PASSWORD=Eidoh5zo
      - MYSQL_DATABASE=osm_hu
    volumes:
      - mysql-data:/var/lib/mysql

  # phpMyAdmin accessible at http://localhost:11780
  mysql-phpmyadmin:
    image: phpmyadmin:5
    ports:
      - 11780:80
    environment:
      - PMA_HOST=mysql-db
      - PMA_USER=osmhu
      - PMA_PASSWORD=Eidoh5zo
    depends_on:
      - mysql-db

  postgresql-db:
    image: postgis/postgis:12-3.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=osmhu
      - POSTGRES_PASSWORD=Eidoh5zo
      - POSTGRES_DB=gis
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  mysql-data:
  postgresql-data:
