GRANT ALL PRIVILEGES ON DATABASE gis TO osmhu;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO osmhu;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO osmhu;
CREATE EXTENSION postgis;
CREATE EXTENSION hstore;
