name: Distribution CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install npm dependencies
      run: npm ci

    - name: Build distribution artifact
      run: make build

    - name: Tar distribution artifact (to preserve file permissions)
      run: tar -cvf distribution.tar distribution

    - name: Upload distribution artifact
      uses: actions/upload-artifact@v2
      with:
        name: distribution
        path: distribution.tar
