name: Lint

on:
  push:
    branches: [ '!main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  lint:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: editorconfig-checker/action-editorconfig-checker@main

      - name: Check if all files meet EditorConfig rules
        run: editorconfig-checker

      - name: Check shell scripts with ShellCheck for errors
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          scandir: './development'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Check if css files meet lint rules
        run: npm run lint:css

      - name: Check if js files meet lint rules
        run: npm run lint:js

      - name: Install PHP dependencies with composer
        uses: php-actions/composer@v6

      - name: Check if PHP files meet coding standards
        run: make lint-php
