name: Lint CI

on:
  push:
    branches: [ '!main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Check if all files meet Editorconfig rules
        uses: editorconfig-checker/action-editorconfig-checker@v1.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Check if js files meet ESLint rules
        run: npm run lint
